
package com.grandland.qdhx.client.app;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SupplyChainServiceImplService", targetNamespace = "http://impl.service.webservice.emanager.ylwj.com/", wsdlLocation = "http://forever.oicp.io:39272/HuaXiaEManager/webService/webSercice_message_push?wsdl")
public class SupplyChainServiceImplService
    extends Service
{

    private final static URL SUPPLYCHAINSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUPPLYCHAINSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SUPPLYCHAINSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.webservice.emanager.ylwj.com/", "SupplyChainServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://forever.oicp.io:39272/HuaXiaEManager/webService/webSercice_message_push?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUPPLYCHAINSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SUPPLYCHAINSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SupplyChainServiceImplService() {
        super(__getWsdlLocation(), SUPPLYCHAINSERVICEIMPLSERVICE_QNAME);
    }

    public SupplyChainServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUPPLYCHAINSERVICEIMPLSERVICE_QNAME, features);
    }

    public SupplyChainServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SUPPLYCHAINSERVICEIMPLSERVICE_QNAME);
    }

    public SupplyChainServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUPPLYCHAINSERVICEIMPLSERVICE_QNAME, features);
    }

    public SupplyChainServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupplyChainServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SupplyChainService
     */
    @WebEndpoint(name = "SupplyChainServiceImplPort")
    public SupplyChainService getSupplyChainServiceImplPort() {
        return super.getPort(new QName("http://impl.service.webservice.emanager.ylwj.com/", "SupplyChainServiceImplPort"), SupplyChainService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SupplyChainService
     */
    @WebEndpoint(name = "SupplyChainServiceImplPort")
    public SupplyChainService getSupplyChainServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.webservice.emanager.ylwj.com/", "SupplyChainServiceImplPort"), SupplyChainService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUPPLYCHAINSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SUPPLYCHAINSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SUPPLYCHAINSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
